name: ReviewApp
on:
    push:
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup-Java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'
            - name: Mvn code test
              run: mvn checkstyle:checkstyle --file pom.xml
            - name: MVN Verify 
              run: mvn verify --file pom.xml 
            - name: Package Artifact
              run: mvn clean install --file pom.xml 
            - name: Upload-artifact
              uses: actions/upload-artifact@v4
              with:
                name: reviewapp-jar
                path: target/ReviewApp-0.0.1-SNAPSHOT.jar

